### PR TITLE
Move WordPress-y files to a subdirectory

### PR DESCRIPTION
**Pull request by szepeviktor**
From #222

# 🧹

### CODE REVIEW

**Comment by szepeviktor** [comment]
@dingo-d Oh nooooooooooooooooo!
This was closed despite highly popular themes go this way.
Please see v2 of https://github.com/timber/starter-theme/tree/2.x

**Comment by iruzevic** [comment]
Sorry this was closed automatically with the release.

**Comment by dingo-d** [comment]
Yeah, if you notice, our boilerplate no longer has any functionality inside it, out of the box 😄 

We are using the libraries to add backend and frontend functionality, and all the business logic is in the `src` folder. For frontend we are using blocks (also in `src`).

**Comment by szepeviktor** [comment]
Still WordPressy and development files are **mixed** in the root directory.

**Comment by dingo-d** [comment]
Yeah, I'm not a big fan of changing the default theme structure. Could mess with child themes and I'd rather move config files to a separate folder than the other way around tbh.

**Comment by szepeviktor** [comment]
Okay-okay.
There is no medicine against personal preferences. :) Even data-driven things are use less.

**Comment by dingo-d** [comment]
Spot on. Without personal preferences, where's the personal touch? 😄

**Pull request closed without merging**
