### PR TITLE
Add phpstan and fix some errors

### LINKED ISSUE #157: Add static analysis
If a developer wants to have robust code here is @phpstan for him/her with WordPress extensions
https://packagist.org/packages/szepeviktor/phpstan-wordpress

- in the /example directory you may find composer.json
- and phpstan config file

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #157 

@dingo-d Could you add `vendor/bin/phpstan analyze` to composer and npm scripts?

⚠️ WordPress core has surprises for you, e.g. Walker_Nav_Menu has big contradictions

### CODE REVIEW

**Comment by szepeviktor** [comment]
> Walker_Nav_Menu has big contradictions

I (or you?) could develop a fix in szepeviktor/phpstan-wordpress

**Comment by szepeviktor** [comment]
Please consider not using non-green PHP versions: https://www.php.net/supported-versions.php 🍏

**Comment by szepeviktor** [comment]
@iruzevic I think you don't like static analysis.

**Comment by pattonwebz** [comment]
@iruzevic The code changes here actually all seem pretty nice to me, even if phpstan isn't rolled in those other changes are still great improvements :)

**Comment by szepeviktor** [comment]
Okay, I open another PR.

**Comment by dingo-d** [comment]
I think my colleague updated the latest code, you can make a new PR, I'll also give it a go and see what else needs to be fixed. 

Thanks for your contributions, we appreciate it 🙂

**Pull request closed without merging**
